import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

const font = Lexend_Deca({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BizSelf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
